{ pkgs, lib, ... }:
let
  # Nix バイナリが必要とする libstdc++ を含むライブラリパス
  nixLdLibraryPath = "${pkgs.stdenv.cc.cc.lib}/lib:/usr/lib/aarch64-linux-gnu";
in
{
  imports = [
    ../common/shell-base.nix
    ../common/starship.nix
    ../common/git.nix
    ../common/claude-code.nix
  ];

  nixpkgs.config.allowUnfreePredicate = pkg:
    builtins.elem (pkgs.lib.getName pkg) [
      "claude-code"
    ];

  home.stateVersion = "24.11";
  home.sessionVariables = {
    # コンテナ環境で未設定の場合があるため明示的に設定
    USER = "quipper";
    NIX_LD = "/lib/ld-linux-aarch64.so.1";
    # Nix の libstdc++ を優先し、システムライブラリをフォールバックとして使用
    NIX_LD_LIBRARY_PATH = nixLdLibraryPath;
  };

  # LD_PRELOAD に設定された共有ライブラリ（jemalloc 等）が Nix 環境と競合するため解除
  programs.zsh.initContent = lib.mkBefore ''
    unset LD_PRELOAD
  '';

  home.packages = with pkgs; [
    # CLI ツール
    ripgrep
    gh

    # 開発ツール
    claude-code

    # Docker（build 用）
    docker-client
    docker-buildx

    # ランタイム
    nodejs_22
    (corepack.overrideAttrs (old: { meta = old.meta // { priority = 0; }; }))
    ruby
  ];

  # zsh ラッパースクリプト
  # シェバンにシステムの /bin/sh を使用（Nix の bash も libstdc++ 問題を抱えるため）
  # LD_PRELOAD（jemalloc 等）が Nix バイナリと競合するため unset
  home.file.".local/bin/zsh" = {
    executable = true;
    text = ''
      #!/bin/sh
      # コンテナ環境で未設定の場合があるため明示的に設定
      export USER="''${USER:-quipper}"
      export HOME="''${HOME:-/home/quipper}"
      # LD_PRELOAD の jemalloc がシステムの libstdc++ に依存するため、Nix 環境と競合する
      unset LD_PRELOAD
      exec ${pkgs.zsh}/bin/zsh "$@"
    '';
  };

  # /etc/profile.d/ に LD_LIBRARY_PATH 設定を追加（ログイン時に全シェルで適用）
  # これにより Nix 以外のツール（ssh 等）から起動した場合も動作する
  home.activation.setupNixLdLibs = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    PROFILE_SCRIPT="/etc/profile.d/nix-ld-libs.sh"
    EXPECTED_CONTENT="export LD_LIBRARY_PATH=\"${nixLdLibraryPath}:\$LD_LIBRARY_PATH\""

    if [ ! -f "$PROFILE_SCRIPT" ] || ! /usr/bin/grep -qF "${pkgs.stdenv.cc.cc.lib}/lib" "$PROFILE_SCRIPT" 2>/dev/null; then
      echo "Setting up $PROFILE_SCRIPT..."
      /usr/bin/sudo tee "$PROFILE_SCRIPT" > /dev/null << 'EOFPROFILE'
# Nix バイナリが必要とする libstdc++ へのパス
# NIX_LD 使用時にシステムの動的リンカーがこのパスを参照する
# Generated by home-manager
export LD_LIBRARY_PATH="${nixLdLibraryPath}:$LD_LIBRARY_PATH"
EOFPROFILE
      /usr/bin/sudo chmod 644 "$PROFILE_SCRIPT"
    fi
  '';

  # デフォルトシェルを zsh ラッパーに変更
  home.activation.setDefaultShell = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
    ZSH_PATH="$HOME/.local/bin/zsh"
    if ! /usr/bin/grep -q "$ZSH_PATH" /etc/shells 2>/dev/null; then
      echo "$ZSH_PATH" | /usr/bin/sudo tee -a /etc/shells
    fi
    if [ "$SHELL" != "$ZSH_PATH" ]; then
      /usr/bin/sudo chsh -s "$ZSH_PATH" "''${USER:-quipper}"
    fi
  '';
}
